config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :studysheets, only: [:index, :new, :create, :show, :edit, :update, :destroy]do
    collection do
      post :confirm
    end
  end

  root 'studysheets#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :studysheets do
    resources :comments
    post :confirm, on: :collection
  end

  get 'studysheets/download/:id'=>'studysheets#download',as: :download_pdf

  resources :users, only: [:index, :show]

  resources :conversations do
  resources :messages
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :studysheet

  has_many :notifications, dependent: :destroy

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # コメントを保存、投稿するためのアクションです。
  def create
    # studysheetをパラメータの値から探し出し,studysheetに紐づくcommentsとしてbuildします。
    @comment = current_user.comments.build(comment_params)
    @studysheet= @comment.studysheet
    @notification = @comment.notifications.build(user_id: @studysheet.user.id )
    # クライアント要求に応じてフォーマットを変更
    respond_to do |format|
      if @comment.save
        format.html { redirect_to studysheet_path(@studysheet), notice: 'コメントを投稿しました。' }
          # JS形式でレスポンスを返します。
        format.js { render :index }
       unless @comment.studysheet.user_id == current_user.id
        Pusher.trigger("user_#{@comment.studysheet.user_id}_channel", 'comment_created', {
          message: 'あなたの作成したブログにコメントが付きました'
        })
      end
      Pusher.trigger("user_#{@comment.studysheet.user_id}_channel", 'notification_created', {
        unread_counts: Notification.where(user_id: @comment.studysheet.user.id, read: false).count
        })
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @studysheet = @comment.studysheet
    respond_to do |format|
      @comment.destroy
      format.html { redirect_to studysheet_path(@studysheet), notice: 'コメントを削除しました。' }
      format.js { render :index }
      end
  end

  def edit
    @comment = Comment.find(params[:id])
    @studysheet = @comment.studysheet
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to studysheet_path(@comment.studysheet), notice: 'コメントを更新しました。'
    else
      render 'edit'
    end
  end

  private
    # ストロングパラメーター
    def comment_params
      params.require(:comment).permit(:studysheet_id, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([studysheet,comment], remote: true) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= comment.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :studysheet_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <%= link_to '', edit_studysheet_comment_path(studysheet, comment), class: "fa fa-pencil-square-o fa-lg" %>
            <%= link_to '', studysheet_comment_path(studysheet, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<div class="container">
    <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">

      <%= render partial: 'comments/form', locals: { comment: @comment, studysheet: @studysheet } %>

    </div>
  </div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.studysheet.comments, studysheet: @comment.studysheet }) %>")
$(':text').val('')