config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :studysheets, only: [:index, :new, :create, :show, :edit, :update, :destroy]do
    collection do
      post :confirm
    end
  end

  root 'studysheets#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :studysheets do
    resources :comments
    post :confirm, on: :collection
  end

  get 'studysheets/download/:id'=>'studysheets#download',as: :download_pdf

  resources :users, only: [:index, :show]

  resources :conversations do
  resources :messages
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  has_many :messages, dependent: :destroy

  has_many :studysheets, dependent: :destroy
  # CommentモデルのAssociationを設定
  has_many :comments, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController  < Devise::OmniauthCallbacksController

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    if current_user.admin == true
      @users = User.all
    else
      @users = User.where("admin = 'true'")
    end
  end

  def show
      @user = User.find(params[:id])
  end

end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container">
  <% if current_user.admin?%>
  <h1>先生/生徒一覧</h1>
  <% else %>
  <h1>先生一覧</h1>
  <% end %>

  <% @users.each do |user| %>
      <div class="container-child col-md-2 col-sm-4 col-xs-6 ">
        <%= link_to user_path(user) do %>
          ユーザ：<%= user.name %>
        <% end %>
      </br>
        <%= profile_img(user) %>
        <% if user.id != current_user.id %>
          <li style="list-style: none">
            <%= link_to '＊メッセージ＊', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post', class: 'btn btn-default'%>
          </li>
         <% end %>
      </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">

  <div class="container-child col-md-12 col-sm-12 col-xs-12" >
  <br>
  <h2>ユーザ情報</h2>
  <br>
  <h4>ユーザ名：<%= @user.name %></h4>
  <br>
  <h4>メール：<%= @user.email %></h4>
  <br>
  <h4>イメージ：<%= profile_img(@user) %></h4>
  <br>

  </div>
</div>