config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :studysheets, only: [:index, :new, :create, :show, :edit, :update, :destroy]do
    collection do
      post :confirm
    end
  end

  root 'studysheets#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :studysheets do
    resources :comments
    post :confirm, on: :collection
  end

  get 'studysheets/download/:id'=>'studysheets#download',as: :download_pdf

  resources :users, only: [:index, :show]

  resources :conversations do
  resources :messages
  end

end

app/models/studysheet.rb
class Studysheet < ActiveRecord::Base
  validates :title, presence: true

  belongs_to :user

  # CommentモデルのAssociationを設定
  has_many :comments, dependent: :destroy

  mount_uploader :image, ImageUploader
end

app/controllers/studysheets_controller.rb
class StudysheetsController < ApplicationController
before_action :authenticate_user!
before_filter :authenticate_user!
before_action :set_studysheet, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.admin == true
      @studysheets = Studysheet.all.order(created_at: :desc)
    else
      @studysheets = current_user.studysheets.all.order(created_at: :desc)
    end
  end

  def show
    if current_user.admin == true
      @comment = @studysheet.comments.build
      @comments = @studysheet.comments
      Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
    else
      if @studysheet.user != current_user
        redirect_to studysheets_path, notice: "作成者しか閲覧できません"
      else
      @comment = @studysheet.comments.build
      @comments = @studysheet.comments
      Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
      end
    end
  end

  def new
    if params[:back]
      @studysheet = Studysheet.new(studysheets_params)
    else
      @studysheet = Studysheet.new
    end
  end

  def create
    @studysheet = Studysheet.create(studysheets_params)
    @studysheet.user_id = current_user.id
    if @studysheet.save
      redirect_to studysheets_path, notice: "作成しました！"
      NoticeMailer.sendmail_studysheet(@studysheet).deliver
    else
      render 'new'
    end
  end

  def edit
    #    @studysheet = Studysheet.find(params[:id])
    if @studysheet.user != current_user
      redirect_to studysheets_path, notice: "作成者しか編集できません"
    end
  end

  def update
#    @studysheet = Studysheet.find(params[:id])
  if @studysheet.user != current_user
    redirect_to studysheets_path, notice: "作成者しか更新できません"
  else
    if @studysheet.update(studysheets_params)
    redirect_to studysheets_path, notice: "更新しました！"
    else
      render 'edit'
    end
  end
  end

  def confirm
    @studysheet = Studysheet.new(studysheets_params)
    render :new if @studysheet.invalid?
  end

  def destroy
#    @studysheet = Studysheet.find(params[:id])
  if @studysheet.user != current_user
    redirect_to studysheets_path, notice: "作成者しか削除できません"
  else
    @studysheet.destroy
    redirect_to studysheets_path, notice: "削除しました！"
  end
  end

  def download
       @studysheet = Studysheet.find(params[:id])
       filepath = @studysheet.image.current_path
       stat = File::stat(filepath)
       sheet=@studysheet.image.url.gsub(/.*\//,'')
       send_file(filepath, :filename => sheet, :length => stat.size)
  end

  private
    def studysheets_params
      params.require(:studysheet).permit(:title, :content, :image, :image_cache)
    end

    def set_studysheet
        @studysheet = Studysheet.find(params[:id])
    end
end

app/helpers/studysheets_helper.rb
module StudysheetsHelper
  def choose_new_or_edit
     if action_name == 'new' || action_name == 'confirm'
       confirm_studysheets_path
     elsif action_name == 'edit'
       studysheet_path
     end
   end
end

app/views/studysheets/_form.html.erb
<%= form_for(@studysheet, url: choose_new_or_edit) do |f| %>
  <% if @studysheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= @studysheet.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @studysheet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.label :title %>
<%= f.text_field :title, class: 'form-control' %>
<br>
<%= f.label :content %>
<%= f.text_field :content, class: 'form-control' %>
<br>
<p>添付:<%= @studysheet.image.url.gsub(/.*\//,'') if @studysheet.image.url.present?%></p>
<%= f.file_field :image %>
<%= f.hidden_field :image_cache %>

<%= f.submit'提出', class: 'btn btn-success btn-block' %>
<% end %>

<%= link_to "勉強状況一覧画面にもどる", studysheets_path %>

app/views/studysheets/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>

    <%= form_for(@studysheet) do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.hidden_field :image %>
      <%= f.hidden_field :image_cache %>

        <p>タイトル:<%= @studysheet.title %></p>
        <p>本文:<%= @studysheet.content %></p>
        <% if @studysheet.image.present? %>
        <p>添付:<%= @studysheet.image.url.gsub(/.*\//,'') %></p>
        <% end %>
        <%= f.submit "登録",class: 'btn btn-success btn-block' %>
        <% end %>

    <%= form_for(@studysheet, url: new_studysheet_path, method: 'get') do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.hidden_field :image %>
      <%= f.hidden_field :image_cache %>
      <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block'  %>
    <% end %>
  </div>
</div>

app/views/studysheets/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <p id="notice"><%= notice %></p>
    <h2>課題を編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/studysheets/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %><%= alert %></p>
    <% if current_user.admin?%>
    <h1>管理ページ</h1>
    <h4>管理者としてログインしています！</h4>
    <% else %>
    <h1>マイページ</h1>
    <h4>毎日の勉強状況を記入しよう！</h4>
      <%= link_to "勉強状況を記入する", new_studysheet_path, class: 'btn btn-default'  %>
    <% end %>

      <% @studysheets.each do |studysheet| %>
      <div class="row">
        <p>氏名:<%= studysheet.user.name %><img src="<%= studysheet.user.image_url %>"></p>
        <p>作成時刻:<%= studysheet.created_at.strftime("%y/%m/%d %p %l:%M") %></p>
        <%= link_to studysheet_path(studysheet) do %>
        <h4><strong><%= studysheet.title %></strong></h4>
        <% end %>
        <p>内容:<%= studysheet.content %></p>
      <% if studysheet.image.present? %>
          <p>添付:<%= studysheet.image.url.gsub(/.*\//,'') %></p>
        　<%= link_to '添付あり',download_pdf_path(studysheet), :class => 'btn btn-sm btn-default', :target=>["_blank"]%>
      <% end %>
      <% if studysheet.user == current_user %>
          <%= link_to "編集", edit_studysheet_path(studysheet.id), class: 'btn btn-sm btn-success'  %>
          <%= link_to '削除', studysheet_path(studysheet.id), method: :delete, data: { confirm: '本当に編集していいですか？' }, class: 'btn btn-sm btn-danger'%>
     <% end %>
        </div>
      <% end %>
      </br>
  </div>
</div>

app/views/studysheets/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <p id="notice"><%= notice %></p>
    <h2>勉強情報を記入する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/studysheets/show.html.erb
<p id="notice"><%= notice %></p>
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="studysheet-text">
      <p class="left"><strong>タイトル</strong></p>
      <p class="left"><%= @studysheet.title %></p>
      <p class="left"><strong>内容</strong></p>
      <p class="left"><%= @studysheet.content %></p>
      <p class="left"><strong>作成者</strong></p>
      <p class="left"><%= @studysheet.user.name %></p>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @studysheet.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    </div>
    <p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, studysheet: @studysheet } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, studysheet: @studysheet } %>
    <% if current_user.id == @studysheet.user_id %>
      <%= link_to '編集', edit_studysheet_path(@studysheet) %> |
    <% end %>
    <%= link_to '戻る', studysheets_path %>
  </div>
</div>