config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :studysheets, only: [:index, :new, :create, :show, :edit, :update, :destroy]do
    collection do
      post :confirm
    end
  end

  root 'studysheets#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :studysheets do
    resources :comments
    post :confirm, on: :collection
  end

  get 'studysheets/download/:id'=>'studysheets#download',as: :download_pdf

  resources :users, only: [:index, :show]

  resources :conversations do
  resources :messages
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
  <title>Studysheet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <% if user_signed_in? %>
      <script>
        var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>',{
          encrypted: true,
          cluster: 'ap1'
        });

        var channel = pusher.subscribe("user_<%= current_user.id %>_channel");
        channel.bind('comment_created', function(data) {
          alert(data.message);
        });
        channel.bind('notification_created', function(data) {
          $('#unread_count').html(data.unread_counts);
        });
      </script>
    <% end %>
</head>

<body>

<header>
  <ul>
    <% if user_signed_in? %>
      <li><%= link_to notifications_index_path, class: "navbar-brand" do %>
        <i class="fa fa-bell fa-1x"><span id="unread_count"><%= @notifications_count %></span></i>
      <% end %></li>
      <li><%= link_to 'マイページ', edit_user_registration_path %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% if current_user.admin?%>
        <li><%= link_to '先生/生徒一覧', users_path%></li>
      <% else %>
        <li><%= link_to '先生一覧', users_path%></li>
      <% end %>
      <li><%=link_to"投稿する",new_studysheet_path %></li>
      <li><%=link_to"投稿一覧",studysheets_path %></li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path  %></li>
      <li><%= link_to 'サインアップ', new_user_registration_path %></li>
    <% end %>
  </ul>
</header>

<%= yield %>

  <footer>
    <p>© 2017 Studysheet, Inc.</p>
  </footer>

</body>
</html>